complete -c pb -s h -l help -f -d "Show help"
complete -c pb -s v -l version -f -d "Show version"
complete -c pb -s c -l color -f -d "Pretty color output"
complete -c pb -s s -l server -x -d "Use alternative pastebin server address"
complete -c pb -s e -l extension -x -d "Specify file extension used in the upload"
complete -c pb -s f -l file -r -d "Explicitly interpret stdin as filename"
