name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Fish
        run: |
          sudo apt-add-repository -yn ppa:fish-shell/release-3
          sudo apt-get update
          sudo apt-get install -y fish

      - name: Install Tools
        run: |
          curl -sL https://git.io/fisher | source
          fisher install jorgebucaran/fishtape $GITHUB_WORKSPACE
      - name: Run tests
        run: |
          fishtape tests/*.fish
        shell: fish {0}
